### Insert a New Cart
POST  http://localhost:3000/cars
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

vanessa
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

avane89@gmail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="designation"

mark/model/2021
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="city"

Bora-Bora
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="numberplate"

ABCDEAQSW
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

256
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="cars2.jpeg"
Content-Type: image/png

< ../Desktop/cars2.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Confirm Email
GET http://localhost:3000/cars/email-confirmation/:token
### Get cars list
GET  http://localhost:3000/cars/list

### Boooking
POST  http://localhost:3000/bookings
Content-Type: application/json

{
    "carId": "a799d5f7-5bcf-4cf3-ad82-5debe160d682",
    "selectedStartDate": "Thu May 07 2023",
    "selectedEndDate": "Thu May 07 2023"
}