### Insert a New Cart
POST  http://localhost:3000/cars
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

vanessa
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

email@email.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="designation"

mark/model/2021
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="city"

Bora-Boras
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="numberplate"

ABCDEAQ
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

256
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="mate.jpeg"
Content-Type: image/png

< ../Desktop/mate.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Confirm Email
GET http://localhost:3000/cars/email-confirmation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXIiOnsiZGVzaWduYXRpb24iOiJtYXJrL21vZGVsLzIwMjEiLCJjaXR5IjoiQm9yYS1Cb3JhIiwibnVtYmVycGxhdGUiOiJBQkNERUFRU1dRUSIsInByaWNlIjoiMjU2IiwicGhvdG9fbmFtZSI6InBob3RvLTE2NzkxNDQ4NzcyNTAtOTk4NjM2MDgxLnBuZyJ9LCJvd25lciI6eyJ1c2VybmFtZSI6InZhbmVzc2EiLCJlbWFpbCI6ImF2YW5lODlAZ21haWwuY29tIn0sImlhdCI6MTY3OTE0NDg3NywiZXhwIjoxNjc5MTQ1MDU3fQ.yxXVEFSm6pd8_g0KTstAl0_wyKFFQHVcYTqW7cDSGDA

### Get cars list
GET  http://localhost:3000/cars/list

### Boooking
POST  http://localhost:3000/bookings
Content-Type: application/json

{
    "carId": "a799d5f7-5bcf-4cf3-ad82-5debe160d682",
    "selectedStartDate": "Thu May 07 2023",
    "selectedEndDate": "Thu May 07 2023"
}

### Get bookings list
GET  http://localhost:3000/bookings/list

### Delete booking
DELETE  http://localhost:3000/bookings/delete/'03fe6464-0cf3-4728-9271-b2173d786787'