### Insert a New Cart
POST  http://localhost:3000/cars
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

vanessa
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

avane89@gmail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="designation"

mark/model/2021
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="city"

Bora-Bora
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="numberplate"

ABCDEAQSW
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

256
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="cars2.jpeg"
Content-Type: image/png

< ../Desktop/cars2.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Confirm Email
GET http://localhost:3000/cars/email-confirmation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXIiOnsiZGVzaWduYXRpb24iOiJtYXJrL21vZGVsLzIwMjEiLCJjaXR5IjoiQm9yYS1Cb3JhIiwibnVtYmVycGxhdGUiOiJBQkNERUZXUSIsInByaWNlIjoiNTYiLCJwaG90b19uYW1lIjoicGhvdG8tMTY3ODg4NzE3OTgwNy0xNDg4MDcwOTMucG5nIn0sIm93bmVyIjp7InVzZXJuYW1lIjoidmFuZXNzYSIsImVtYWlsIjoiYXZhbmU4OUBnbWFpbC5jb20ifSwiaWF0IjoxNjc4ODg3MTc5LCJleHAiOjE2Nzg4ODcyMzl9.dFpyXtdX4TLae7FJvOP7QySc1QVvAQXqQvp37yJsHS0

### Get cars list
GET  http://localhost:3000/cars/list